name: owl_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  http: ^0.13.4
  get_storage: ^2.0.3
  image_picker: ^0.8.5
  #image_cropper: ^1.5.1
 # flutter_image_compress: ^1.1.0
  supabase_flutter: 0.2.12
  supabase: ^0.2.15
  file_picker: ^4.5.1

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - lib/app/assets/img/

